baseurl = "https://blog.lizhimiao.com/"
languageCode = "zh-CN"
theme = "hugo-theme-stack"
paginate = 5
title = "lizhimiao的博客"
disqusShortname = "hugo-theme-stack"            # Change it to your Disqus shortname before using
DefaultContentLanguage = "en"                   # Theme i18n support

[permalinks]
    post = "/:year/:slug/"
    page = "/:slug/"
    
[params]
    mainSections = ["posts"]
    featuredImageField = "image"
    [params.dateFormat]
        published = "Jan 02, 2006"
        lastUpdated = "Jan 02, 2006 15:04 MST"
    [params.sidebar]
        emoji = "🍥"
        avatar = "img/avatar.png"
        subtitle = "笔记本."
    [params.article]
        [params.article.license]
            enabled = false 
            default = "Licenced under CC BY-NC-SA 4.0"
    [params.comments]
        enabled = true
        # Only Disqus is available so far
        provider = "disqus"
    [params.widgets]
        enabled = ['archive', 'tag-cloud']
        [params.widgets.archive]
            limit = 5
            ### Archive page relative URL
            path = "archive"       
        [params.widgets.tagCloud]
            limit = 10
    [params.opengraph]
        [params.opengraph.twitter]
            site = ""
            card = "summary_large_image"
    [params.defaultImage]
        [params.defaultImage.article]
            enabled = false
            local = false
            src = ""
        [params.defaultImage.articleList]
            enabled = false
            local = true
            src = ""
        [params.defaultImage.opengraph]
            enabled = false
            local = false
            src = ""
            
[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = -100
        pre = "home"
    [[menu.main]]
        identifier = "about-cn"
        name = "About"
        url = "/about/"
        weight = -90
        pre = "user"
    [[menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive/"
        weight = -70
        pre = "archive"

[related]
    includeNewer = true
    threshold = 60
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 200