[en]
  title = "lizhimiao‘s Blog"
  languageName = "English"
  weight = 2
  languagedir = "en"
  contentdir = "content/en"

[zh]
  title = "lizhimiao的博客"
  languageName = "中文"
  weight = 1
  languagedir = "zh"
  contentdir = "content/zh"
